workflows:
  version: 2
  pipeline:
    jobs:
      - checkout_code:
          filters:
            branches:
              only:
                - master
      - compile:
          requires:
            - checkout_code
      - unit_test:
          requires:
            - compile
      - integration_test:
          requires:
            - compile
      - acceptance_test:
          requires:
            - compile
      - package:
          requires:
            - unit_test
            - integration_test
            - acceptance_test
      - generate_docker_image:
          requires:
            - package
      - merge_with_master:
          requires:
            - generate_docker_image


version: 2

jobs:
  #Phases

  checkout_code:
    <<: *mavenAndworkdir

    steps:
      - checkout

      # Fetch all git submodules
      - run: git submodule sync
      - run: git submodule update --init --recursive

      - *save_cache_configuration

  ## Phase Resolve Deps
  compile:
    <<: *mavenAndworkdir

    steps:
      - *restore_cache_configuration

      # Download and cache dependencies
      - run: mvn clean compile

      - *save_cache_configuration

  ## Compile and Run Test Suite
  unit_test:
    <<: *mavenAndworkdir


    steps:
      - *restore_cache_configuration

      # run tests!
      - run: mvn test

      - *save_cache_configuration

  integration_test:
    <<: *mavenAndworkdir

    steps:
      - *restore_cache_configuration

      # run tests!
      - run: mvn test

      - *save_cache_configuration

  acceptance_test:
    <<: *mavenAndworkdir

    steps:
      - *restore_cache_configuration

      # run tests!
      - run: mvn test

      - *save_cache_configuration

  ## Packaging
  package:
    <<: *mavenAndworkdir

    steps:
      - *restore_cache_configuration

      # package all modules
      - run: mvn package -DSkipTest

      - *save_cache_configuration


  ## Build Application Container Image
  generate_docker_image:
    docker:
        - image: docker:17.12.0-ce-git

    working_directory: ~/project

    steps:
      - *restore_cache_configuration

      - run: find . -name "*.jar"
      - run: docker --version

      - *save_cache_configuration

  #Send to Production
  merge_with_master:
    docker:
        - image: docker:17.12.0-ce-git
    working_directory: ~/project
    steps:
      - *restore_cache_configuration

      - run: ls
      - run: git status

      - *save_cache_configuration

# Anchors
mavenAndworkdir: &mavenAndworkdir
  docker:
      # specify the version you desire here
      - image: circleci/openjdk:9-jdk

  environment:
    # Customize the JVM maximum heap limit
    MAVEN_OPTS: -Xmx3200m

  working_directory: ~/project


restore_cache_configuration: &restore_cache_configuration
    restore_cache:
        keys:
        - repo-{{ .Environment.CIRCLE_SHA1 }}
        - dependencies-{{ checksum "pom.xml" }}
        # fallback to using the latest cache if no exact match is found
        - dependencies-

save_cache_configuration: &save_cache_configuration
    # Save project status
    save_cache:
        key: repo-{{ .Environment.CIRCLE_SHA1 }}
        paths:
          - ~/project
    # Save sonar and maven dependencies
    save_cache:
        key: dependencies-{{ checksum "pom.xml" }}
        paths:
          - ~/.m2/repository
          - ~/.sonar/cache
