version: 2


anchors_references:

  sonar_integration: &sonar_integration
    - SONAR_INTEGRATION: yes
  docker_integration: &docker_integration
    - DOCKER_INTEGRATION: yes

  maven_container_configuration: &maven_container_configuration
    docker:
        # specify the version you desire here
        - image: circleci/openjdk:9-jdk
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    working_directory: ~/project

  maven_and_docker_container_configuration: &maven_and_docker_container_configuration
    docker:
        # specify the version you desire here
        - image: circleci/openjdk:9-jdk
        - image: docker:17.12.0-ce-git

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    working_directory: ~/project

  restore_repo_cache: &restore_repo_cache
      restore_cache:
          keys:
          - repo-{{ .Branch }}-{{ .Revision }}
          # fallback to using the latest cache if no exact match is found
          - repo-{{ .Branch }}
          - repo-
  restore_dependencies_cache: &restore_dependencies_cache
      restore_cache:
          keys:
          - dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-
  restore_sonar_cache: &restore_sonar_cache
      restore_cache:
          keys:
          - sonar-{{ .Environment.CIRCLE_SHA1 }}
          # fallback to using the latest cache if no exact match is found
          - sonar-
  save_repo_cache: &save_repo_cache
      # Save project status
      save_cache:
          key: repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
  save_dependencies_cache: &save_dependencies_cache
      # Save maven dependencies
      save_cache:
          key: dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository
            - ~/.sonar/cache

  save_sonar_cache: &save_sonar_cache
      # Save sonar cache
      save_cache:
          key: sonar-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/.sonar/cache


workflows:
  version: 2
  pipeline:
    jobs:
      - checkout_code:
          filters:
            branches:
              only:
                - master
      - compile:
          requires:
            - checkout_code
      - unit_test:
          requires:
            - compile
      - integration_test:
          requires:
            - compile
      - acceptance_test:
          requires:
            - compile
      - package:
          requires:
            - unit_test
            - integration_test
            - acceptance_test
      - publish_docker_image:
          requires:
            - package
      - merge_with_master:
          filters:
            branches:
              only:
                - release
          requires:
            - publish_docker_image




jobs:
  #Phases

  checkout_code:
    <<: *maven_container_configuration

    steps:
      - checkout

      # Fetch all git submodules
      - run: git submodule sync
      - run: git submodule update --init --recursive

      - *save_repo_cache

  ## Phase Resolve Deps
  compile:
    <<: *maven_container_configuration

    steps:
      - *restore_repo_cache

      # Download and cache dependencies
      - run: mvn clean compile

      - *save_dependencies_cache


  ## Compile and Run Test Suite
  unit_test:
    <<: *maven_container_configuration

    environment:
      - *sonar_integration

    steps:
      - *restore_repo_cache
      - *restore_dependencies_cache
      - *restore_sonar_cache

      # run tests!
      - run: mvn test

      - *save_dependencies_cache
      - *save_sonar_cache

  integration_test:
    <<: *maven_container_configuration

    environment:
      - *sonar_integration

    steps:
      - *restore_repo_cache
      - *restore_dependencies_cache
      - *restore_sonar_cache

      # run tests!
      - run: mvn test

      - *save_dependencies_cache
      - *save_sonar_cache

  acceptance_test:
    <<: *maven_container_configuration

    environment:
      - *sonar_integration

    steps:
      - *restore_repo_cache
      - *restore_dependencies_cache
      - *restore_sonar_cache

      # run tests!
      - run: mvn test

      - *save_dependencies_cache
      - *save_sonar_cache

  ## Packaging
  package:
    <<: *maven_and_docker_container_configuration

    environment:
      - *docker_integration

    steps:
      - *restore_repo_cache
      - *restore_dependencies_cache

      - setup_remote_docker

      # package all modules
      - run: mvn package -DskipTests

      - *save_dependencies_cache
      - *save_repo_cache


  ## Build Application Container Image
  publish_docker_image:
    <<: *maven_and_docker_container_configuration

    steps:
      - *restore_repo_cache
      - setup_remote_docker

      - run: find . -name "*.jar"
      - run: docker --version

  #Send to Production
  merge_with_master:
    <<: *maven_and_docker_container_configuration

    working_directory: ~/project/mog-backend

    steps:
      - *restore_repo_cache

      - run: ls
      - run: env