version: 2


anchors_references:

  sonar_integration: &sonar_integration
    - SONAR_INTEGRATION: yes

  docker_integration: &docker_integration
    - DOCKER_INTEGRATION: yes

  maven_opts: &maven_opts
    # Customize the JVM maximum heap limit
    - MAVEN_OPTS: -Xmx3200m


  set_workdir: &set_workdir
    working_directory: ~/project



  maven_container_configuration: &maven_container_configuration
    docker:
        # specify the version you desire here
        - image: circleci/openjdk:9-jdk
    environment:
      - *maven_opts

    <<: *set_workdir

  maven_and_docker_container_configuration: &maven_and_docker_container_configuration
    docker:
        # specify the version you desire here
        - image: circleci/openjdk:9-jdk
        - image: docker:17.12.0-ce-git

    environment:
      - *maven_opts

    <<: *set_workdir

  restore_repo_cache: &restore_repo_cache
      restore_cache:
          keys:
          - repo-{{ .Branch }}-{{ .Revision }}
          # fallback to using the latest cache if no exact match is found
          - repo-{{ .Branch }}
          - repo-
  restore_dependencies_cache: &restore_dependencies_cache
      restore_cache:
          keys:
          - dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-
  restore_sonar_cache: &restore_sonar_cache
      restore_cache:
          keys:
          - sonar-{{ .Environment.CIRCLE_SHA1 }}
          # fallback to using the latest cache if no exact match is found
          - sonar-
  save_repo_cache: &save_repo_cache
      # Save project status
      save_cache:
          key: repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/project
  save_dependencies_cache: &save_dependencies_cache
      # Save maven dependencies
      save_cache:
          key: dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2/repository
            - ~/.sonar/cache

  save_sonar_cache: &save_sonar_cache
      # Save sonar cache
      save_cache:
          key: sonar-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/.sonar/cache

  save_application_surefire_report: &save_application_surefire_report
      store_test_results:
          path: application/target/surefire-reports

  save_domain_surefire_report: &save_domain_surefire_report
      store_test_results:
          path: domain/target/surefire-reports

  save_infra_surefire_report: &save_infra_surefire_report
      store_test_results:
          path: infra/target/surefire-reports
workflows:
  version: 2
  pipeline:
    jobs:
      - checkout_code:
          filters:
            branches:
              ignore:
                - master
      - compile:
          filters:
            branches:
              ignore:
                - master
          requires:
            - checkout_code
      - unit_test:
          filters:
            branches:
              ignore:
                - master
          requires:
            - compile
      - integration_test:
          filters:
            branches:
              only:
                - release
                - hotfix
          requires:
            - compile
      - acceptance_test:
          filters:
            branches:
              only:
                - release
                - hotfix
          requires:
            - compile
      - package:
          filters:
            branches:
              only:
                - release
                - hotfix
          requires:
            - unit_test
            - integration_test
            - acceptance_test
      - hotfix_approval:
          type: approval
          filters:
            branches:
              only:
                - hotfix
          requires:
            - package
      - merge_with_master:
          filters:
            branches:
              only:
                - release
                - hotfix
          requires:
            - hotfix_approval
            - package





jobs:
  #Phases

  checkout_code:
    <<: *maven_container_configuration

    steps:
      - checkout

      # Fetch all git submodules
      - run: git submodule sync
      - run: git submodule update --init --recursive

      - *save_repo_cache

  ## Phase Resolve Deps
  compile:
    <<: *maven_container_configuration

    steps:
      - *restore_repo_cache

      # Download and cache dependencies
      - run:
          name: Compile Project
          command: mvn clean compile

      - *save_dependencies_cache


  ## Compile and Run Test Suite
  unit_test:
    <<: *maven_container_configuration

    environment:
      - *sonar_integration

    steps:
      - *restore_repo_cache
      - *restore_dependencies_cache
      - *restore_sonar_cache

      # run tests!
      - run:
          name: Running unit tests
          command: mvn clean test "-Dtest=!%regex[.*(integrations|acceptances).*Test.class]" -DfailIfNoTests=false

      - *save_application_surefire_report
      - *save_domain_surefire_report
      - *save_infra_surefire_report

      - *save_dependencies_cache
      - *save_sonar_cache

  integration_test:
    <<: *maven_container_configuration

    environment:
      - *sonar_integration

    steps:
      - *restore_repo_cache
      - *restore_dependencies_cache
      - *restore_sonar_cache

      # run tests!
      - run:
          name: Running integration tests
          command: mvn clean test "-Dtest=%regex[.*integrations.*Test.class]" -DfailIfNoTests=false

      - *save_application_surefire_report
      - *save_domain_surefire_report
      - *save_infra_surefire_report

      - *save_dependencies_cache
      - *save_sonar_cache

  acceptance_test:
    <<: *maven_container_configuration

    environment:
      - *sonar_integration

    steps:
      - *restore_repo_cache
      - *restore_dependencies_cache
      - *restore_sonar_cache

      # run tests!
      - run:
          name: Running acceptance tests
          command: mvn clean test "-Dtest=%regex[.*acceptances.*Test.class]" -DfailIfNoTests=false

      - *save_application_surefire_report
      - *save_domain_surefire_report
      - *save_infra_surefire_report

      - *save_dependencies_cache
      - *save_sonar_cache

  ## Packaging
  package:
    <<: *maven_container_configuration

    steps:
      - *restore_repo_cache

      - run:
          name: Packaging application
          command: mvn package -DskipTests

      - store_artifacts:
          path: application/target/application-1.0-SNAPSHOT.jar



  #Send to Production
  merge_with_master:
    <<: *maven_and_docker_container_configuration

    environment:
      - *docker_integration

    steps:
      - setup_remote_docker

      - add_ssh_keys:
          fingerprints:
            - "fb:01:d9:c1:7e:74:c3:d9:aa:89:d9:bc:92:cc:1f:e3"

      - checkout

      # Fetch all git submodules
      - run: git submodule sync
      - run: git submodule update --init --recursive

      - *restore_dependencies_cache

      - run: git rebase $CIRCLE_BRANCH
      - run: git push origin master

      - run:
          name: Generating Docker Image
          command: mvn -s settings.xml package -DskipTests -Dmog.docker.currentTag=$CIRCLE_WORKFLOW_ID

      - *save_dependencies_cache
